baseURL = 'https://shawshubham.github.io/'
languageCode = 'en-us'
title = 'The Shubham Co'
theme = 'theshubhamco-theme'
[mediaTypes."text/html"]
  suffixes = ["html"]
[outputFormats.HTML]
  mediaType = "text/html"
  baseName = "index"