baseURL = 'https://shawshubham.github.io/'
languageCode = 'en-us'
title = 'The Shubham Co'
theme = 'theshubhamco-theme'
[mediaTypes."text/html"]
  suffixes = ["html"]
[outputFormats.HTML]
  mediaType = "text/html"
  baseName = "index"
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
enableGitInfo = true

[frontmatter]
lastmod = [":git", "lastmod", ":fileModTime", ":default"]